
services:
  whoasr-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    volumes:
      - whoasr-models:/app/models/cache
      - ./.env:/app/.env:ro

volumes:
  whoasr-models: