[project]
name = "whoasr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "funasr==1.2.9",
    "modelscope==1.30.0",
    "transformers>=4.40.0,<5.0.0",
    "pyaudio",
    "numpy",
    "fastapi",
    "pydantic-settings",
    "uvicorn[standard]",
    "websockets",
    "psutil",
    "python-multipart",
]

[project.optional-dependencies]
cpu = [
    "torch==2.6.0+cpu",
    "torchaudio==2.6.0+cpu",
    "torchvision==0.21.0+cpu",
]
gpu = [
    "torch==2.6.0+cu124",
    "torchaudio==2.6.0+cu124",
    "torchvision==0.21.0+cu124",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-gpu", extra = "gpu" },
]
torchaudio = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-gpu", extra = "gpu" },
]
torchvision = [
    { index = "pytorch-cpu", extra = "cpu" },
    { index = "pytorch-gpu", extra = "gpu" },
]

[tool.uv]
conflicts = [
    [{ extra = "cpu" }, { extra = "gpu" }],
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[[tool.uv.index]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
